import { describe, expect, it } from "vitest";
import { UnsupportedDeviceError, renderAllConfigs, renderFortiGateConfig } from "../src/render.js";
import { g1Design, g4Design } from "./fixtures.js";

describe("renderFortiGateConfig — G1 branch-office firewall", () => {
  const fw = g1Design.devices.find((d) => d.id === "fw-01")!;
  const config = renderFortiGateConfig(fw, g1Design);

  it("starts with the lab-validation banner as a FortiOS (#) comment, not a cisco (!) one", () => {
    expect(config.startsWith("# Base configuration generated by NetDesign.app — validate in a lab before production.")).toBe(
      true,
    );
    expect(config).not.toContain("! Base configuration");
  });

  it("sets the hostname", () => {
    expect(config).toContain('config system global\n    set hostname "fw-01"\nend');
  });

  it("configures port1 as the WAN uplink via DHCP (the ISP link isn't ours to address)", () => {
    expect(config).toContain('edit "port1"\n        set alias "wan-uplink"\n        set mode dhcp');
    // WAN must not be given a hardcoded static address — scope the check to port1's own block
    const port1Block = config.slice(config.indexOf('edit "port1"'), config.indexOf("    next"));
    expect(port1Block).not.toContain("set mode static");
  });

  it("configures each router-facing interface with its real /31 address", () => {
    expect(config).toContain(
      'edit "port2"\n        set alias "Firewall uplink to rtr-01"\n        set mode static\n        set ip 10.30.1.4 255.255.255.254\n        set allowaccess ping',
    );
    expect(config).toContain(
      'edit "port3"\n        set alias "Firewall uplink to rtr-02"\n        set mode static\n        set ip 10.30.1.6 255.255.255.254\n        set allowaccess ping',
    );
  });

  it("adds ECMP static routes to every VLAN subnet via BOTH router peer IPs", () => {
    // corp-data 10.30.2.0/24 via rtr-01 (10.30.1.5/port2) and rtr-02 (10.30.1.7/port3)
    expect(config).toContain('set dst 10.30.2.0 255.255.255.0\n        set gateway 10.30.1.5\n        set device "port2"');
    expect(config).toContain('set dst 10.30.2.0 255.255.255.0\n        set gateway 10.30.1.7\n        set device "port3"');
    // voice + guest reachable via both routers too
    for (const subnet of ["10.30.3.0", "10.30.4.0"]) {
      expect(config).toContain(`set dst ${subnet} 255.255.255.0\n        set gateway 10.30.1.5`);
      expect(config).toContain(`set dst ${subnet} 255.255.255.0\n        set gateway 10.30.1.7`);
    }
    // 3 VLANs x 2 routers = 6 routes
    expect((config.match(/edit \d+\n        set dst/g) ?? [])).toHaveLength(6);
  });

  it("writes no firewall policies (founder's posture: interfaces + routing only)", () => {
    expect(config).not.toContain("config firewall policy");
  });
});

describe("renderFortiGateConfig — G4 single-router firewall", () => {
  const fw = g4Design.devices.find((d) => d.id === "fw-01")!;
  const config = renderFortiGateConfig(fw, g4Design);

  it("routes each VLAN subnet via the single router (no ECMP when there's one router)", () => {
    // G4 has one router, so one route per VLAN subnet
    const routeCount = (config.match(/edit \d+\n        set dst/g) ?? []).length;
    expect(routeCount).toBe(g4Design.segments.length);
  });
});

describe("renderFortiGateConfig error handling", () => {
  it("throws UnsupportedDeviceError for a non-fortinet vendor", () => {
    const router = g1Design.devices.find((d) => d.id === "rtr-01")!;
    expect(() => renderFortiGateConfig(router, g1Design)).toThrow(UnsupportedDeviceError);
    expect(() => renderFortiGateConfig(router, g1Design)).toThrow(/vendorHint "fortinet-fortigate"/);
  });

  it("throws UnsupportedDeviceError for a fortinet device with an unsupported role", () => {
    const fakeSwitch = { ...g1Design.devices.find((d) => d.id === "fw-01")!, id: "fgt-sw", role: "access-switch" as const };
    expect(() => renderFortiGateConfig(fakeSwitch, g1Design)).toThrow(/no fortinet-fortigate template for role "access-switch"/);
  });
});

describe("renderAllConfigs includes the Fortinet firewall", () => {
  it("now renders fw-01 alongside the cisco devices", () => {
    expect(Object.keys(renderAllConfigs(g1Design))).toContain("fw-01");
  });
});
