import { describe, expect, it } from "vitest";
import { UnsupportedDeviceError, renderAllConfigs, renderPanOsConfig } from "../src/render.js";
import { g1Design, g1PanosDesign, g4PanosDesign } from "./fixtures.js";

describe("renderPanOsConfig — G1 branch-office firewall", () => {
  const fw = g1PanosDesign.devices.find((d) => d.id === "fw-01")!;
  const config = renderPanOsConfig(fw, g1PanosDesign);

  it("starts with the lab-validation banner as a PAN-OS (#) comment, not a cisco (!) one", () => {
    expect(config.startsWith("# Base configuration generated by NetDesign.app — validate in a lab before production.")).toBe(
      true,
    );
    expect(config).not.toContain("! Base configuration");
  });

  it("sets the hostname", () => {
    expect(config).toContain("set deviceconfig system hostname fw-01");
  });

  it("configures ethernet1/1 as the WAN uplink via DHCP (the ISP link isn't ours to address)", () => {
    expect(config).toContain("set network interface ethernet ethernet1/1 layer3 dhcp-client enable yes");
    expect(config).toContain("set network interface ethernet ethernet1/1 layer3 dhcp-client create-default-route yes");
    // The WAN must not be given a hardcoded static address
    expect(config).not.toContain("set network interface ethernet ethernet1/1 layer3 ip ");
  });

  it("configures each router-facing interface with its real /31 address in CIDR form", () => {
    expect(config).toContain("set network interface ethernet ethernet1/2 layer3 ip 10.30.1.4/31");
    expect(config).toContain("set network interface ethernet ethernet1/3 layer3 ip 10.30.1.6/31");
    expect(config).toContain('set network interface ethernet ethernet1/2 comment "Firewall uplink to rtr-01"');
    expect(config).toContain('set network interface ethernet ethernet1/3 comment "Firewall uplink to rtr-02"');
  });

  it("permits ping on the inside interfaces only, via an interface management profile", () => {
    expect(config).toContain("set network profiles interface-management-profile allow-ping ping yes");
    expect(config).toContain("set network interface ethernet ethernet1/2 layer3 interface-management-profile allow-ping");
    expect(config).toContain("set network interface ethernet ethernet1/3 layer3 interface-management-profile allow-ping");
    expect(config).not.toContain("set network interface ethernet ethernet1/1 layer3 interface-management-profile");
  });

  it("puts the WAN in untrust and every inside interface in trust", () => {
    expect(config).toContain("set zone untrust network layer3 ethernet1/1");
    expect(config).toContain("set zone trust network layer3 ethernet1/2");
    expect(config).toContain("set zone trust network layer3 ethernet1/3");
    expect(config).not.toContain("set zone untrust network layer3 ethernet1/2");
  });

  it("imports every interface into vsys1 and the default virtual router", () => {
    for (const iface of ["ethernet1/1", "ethernet1/2", "ethernet1/3"]) {
      expect(config).toContain(`set vsys vsys1 import network interface ${iface}`);
      expect(config).toContain(`set network virtual-router default interface ${iface}`);
    }
  });

  it("adds static routes to every VLAN subnet via BOTH router peer IPs, with ECMP enabled", () => {
    // corp-data 10.30.2.0/24 via rtr-01 (10.30.1.5 / ethernet1/2) and rtr-02 (10.30.1.7 / ethernet1/3)
    expect(config).toContain(
      'set network virtual-router default routing-table ip static-route "corp-data-via-ethernet1-2" destination 10.30.2.0/24',
    );
    expect(config).toContain(
      'set network virtual-router default routing-table ip static-route "corp-data-via-ethernet1-2" nexthop ip-address 10.30.1.5',
    );
    expect(config).toContain(
      'set network virtual-router default routing-table ip static-route "corp-data-via-ethernet1-3" nexthop ip-address 10.30.1.7',
    );
    // voice + guest reachable via both routers too
    for (const subnet of ["10.30.3.0/24", "10.30.4.0/24"]) {
      expect(config).toContain(`destination ${subnet}`);
    }
    // 3 VLANs x 2 routers = 6 routes, each written as 4 leaf `set` lines
    const routeNames = new Set(
      [...config.matchAll(/static-route "([^"]+)"/g)].map((match) => match[1]),
    );
    expect(routeNames.size).toBe(6);
    expect(config).toContain("set network virtual-router default ecmp enable yes");
  });

  it("names routes with PAN-OS-legal characters (no '/' from the interface name)", () => {
    for (const [, name] of config.matchAll(/static-route "([^"]+)"/g)) {
      expect(name).toMatch(/^[A-Za-z0-9._-]+$/);
    }
  });

  it("writes no security policies and no NAT (same posture as the FortiGate template)", () => {
    expect(config).not.toContain("set rulebase security");
    expect(config).not.toContain("set rulebase nat");
  });
});

describe("renderPanOsConfig — rendered output", () => {
  it("snapshots the whole G1 PAN-OS edge config (the artifact the founder reviews line-by-line)", () => {
    const fw = g1PanosDesign.devices.find((d) => d.id === "fw-01")!;
    expect(renderPanOsConfig(fw, g1PanosDesign)).toMatchSnapshot();
  });
});

describe("renderPanOsConfig — G4 single-router firewall", () => {
  const fw = g4PanosDesign.devices.find((d) => d.id === "fw-01")!;
  const config = renderPanOsConfig(fw, g4PanosDesign);

  it("routes each VLAN subnet via the single router (one route per subnet)", () => {
    const routeNames = new Set([...config.matchAll(/static-route "([^"]+)"/g)].map((match) => match[1]));
    expect(routeNames.size).toBe(g4PanosDesign.segments.length);
  });

  it("does not enable ECMP when there is only one next hop", () => {
    expect(config).not.toContain("ecmp enable yes");
  });
});

describe("renderPanOsConfig error handling", () => {
  it("throws UnsupportedDeviceError for a non-palo-alto vendor", () => {
    const router = g1PanosDesign.devices.find((d) => d.id === "rtr-01")!;
    expect(() => renderPanOsConfig(router, g1PanosDesign)).toThrow(UnsupportedDeviceError);
    expect(() => renderPanOsConfig(router, g1PanosDesign)).toThrow(/vendorHint "paloalto-panos"/);
  });

  it("throws UnsupportedDeviceError for a palo-alto device with an unsupported role", () => {
    const fakeSwitch = {
      ...g1PanosDesign.devices.find((d) => d.id === "fw-01")!,
      id: "pan-sw",
      role: "access-switch" as const,
    };
    expect(() => renderPanOsConfig(fakeSwitch, g1PanosDesign)).toThrow(/no paloalto-panos template for role "access-switch"/);
  });
});

describe("renderAllConfigs vendor dispatch", () => {
  it("renders the Palo Alto firewall alongside the cisco devices", () => {
    const configs = renderAllConfigs(g1PanosDesign);
    expect(Object.keys(configs)).toContain("fw-01");
    expect(configs["fw-01"]).toContain("set deviceconfig system hostname fw-01");
  });

  it("still renders a FortiGate edge as FortiOS, not PAN-OS", () => {
    expect(renderAllConfigs(g1Design)["fw-01"]).toContain("config system global");
  });
});
