import type { Design, Device } from "@netdesign/schema";
import { cidrToIpAndMask } from "./cidr.js";

/**
 * FortiOS uses `#` for comments (not cisco's `!`), so the mandated
 * lab-validation banner is rendered as a `#` line here — a `!` line would be
 * an invalid command on the first line of a FortiGate paste. Same sentence,
 * same intent (every config is clearly marked generated + lab-validation
 * required), vendor-correct comment character.
 */
export const FORTIGATE_BANNER =
  "# Base configuration generated by NetDesign AI — validate in a lab before production.";

export interface FortiGateInterfaceView {
  /** FortiGate port name: port1 (WAN) then port2, port3… for the modeled inside links. */
  name: string;
  alias: string;
  mode: "dhcp" | "static";
  ip?: string;
  netmask?: string;
  allowaccess?: string;
}

export interface FortiGateStaticRouteView {
  seq: number;
  dst: string;
  netmask: string;
  gateway: string;
  device: string;
}

export interface FortiGateView {
  banner: string;
  hostname: string;
  interfaces: FortiGateInterfaceView[];
  staticRoutes: FortiGateStaticRouteView[];
}

/**
 * Builds the view model for a fortinet-fortigate edge firewall, per the
 * founder's chosen posture:
 *  - port1 is the WAN uplink as a DHCP client (the ISP link isn't ours to
 *    address, so there's nothing to hardcode).
 *  - Each modeled router-facing interface (device.interfaces with an ip)
 *    becomes a static inside port (port2, port3, …).
 *  - ECMP static routes: one route to each VLAN subnet via BOTH router /31
 *    peer IPs, so the site survives a single router loss (matching HSRP intent).
 *  - No firewall policies — interfaces + routing only (founder's call);
 *    policy is left to the engineer.
 */
export function buildFortiGateView(device: Device, design: Design): FortiGateView {
  const modeled = (device.interfaces ?? []).filter((iface) => iface.ip);

  const interfaces: FortiGateInterfaceView[] = [{ name: "port1", alias: "wan-uplink", mode: "dhcp" }];
  const routerPorts: Array<{ portName: string; peerIp: string }> = [];

  modeled.forEach((iface, index) => {
    const portName = `port${index + 2}`;
    const { ip, netmask } = cidrToIpAndMask(iface.ip!);
    interfaces.push({ name: portName, alias: iface.description ?? portName, mode: "static", ip, netmask, allowaccess: "ping" });

    const peerIp = routerPeerIp(device, iface.name, design);
    if (peerIp) {
      routerPorts.push({ portName, peerIp });
    }
  });

  const staticRoutes: FortiGateStaticRouteView[] = [];
  let seq = 1;
  for (const segment of design.segments) {
    if (!segment.cidr) continue;
    const { ip, netmask } = cidrToIpAndMask(segment.cidr);
    for (const routerPort of routerPorts) {
      staticRoutes.push({ seq: seq++, dst: ip, netmask, gateway: routerPort.peerIp, device: routerPort.portName });
    }
  }

  return { banner: FORTIGATE_BANNER, hostname: device.hostname ?? device.id, interfaces, staticRoutes };
}

/** Finds the IP of the router on the far end of this firewall interface's P2P link — the ECMP next hop toward the LAN. */
function routerPeerIp(device: Device, ifaceName: string, design: Design): string | null {
  for (const link of design.links) {
    const [aId, aIface] = splitEndpoint(link.a);
    const [bId, bIface] = splitEndpoint(link.b);

    let peerId: string | undefined;
    let peerIface: string | undefined;
    if (aId === device.id && aIface === ifaceName) {
      [peerId, peerIface] = [bId, bIface];
    } else if (bId === device.id && bIface === ifaceName) {
      [peerId, peerIface] = [aId, aIface];
    } else {
      continue;
    }

    const peer = design.devices.find((d) => d.id === peerId);
    if (peer?.role !== "router") return null;
    const iface = (peer.interfaces ?? []).find((i) => i.name === peerIface);
    return iface?.ip ? cidrToIpAndMask(iface.ip).ip : null;
  }
  return null;
}

function splitEndpoint(endpoint: string): [string, string | undefined] {
  const [id, iface] = endpoint.split(":");
  return [id ?? endpoint, iface];
}
