import type { Design, Device } from "@netdesign/schema";
import { routerPeerIp } from "./peers.js";

/**
 * PAN-OS `set`-format configs are pasted into `configure` mode, which has no
 * cisco-style `!` comment character; `#` is the convention used in Palo Alto
 * set-command snippets (and what FortiOS uses here too). Same sentence, same
 * intent as the cisco banner — vendor-appropriate comment character.
 */
export const PANOS_BANNER =
  "# Base configuration generated by NetDesign.app — validate in a lab before production.";

/** PAN-OS names the untrusted (internet-facing) and trusted (inside) security zones. */
export const PANOS_UNTRUST_ZONE = "untrust";
export const PANOS_TRUST_ZONE = "trust";
/** Interface management profile granting ping only — the PAN-OS analogue of FortiOS `set allowaccess ping`. */
export const PANOS_PING_PROFILE = "allow-ping";
/** PAN-OS ships with a virtual router called "default"; this design has a single routing domain, so it reuses it. */
export const PANOS_VIRTUAL_ROUTER = "default";
/** PAN-OS's own default static-route metric — emitted explicitly so the config is self-describing. */
export const PANOS_ROUTE_METRIC = 10;

export interface PanOsInterfaceView {
  /** PAN-OS interface name: ethernet1/1 (WAN) then ethernet1/2, ethernet1/3… for the modeled inside links. */
  name: string;
  comment: string;
  mode: "dhcp" | "static";
  /** PAN-OS takes an interface address in CIDR notation, so no netmask conversion is needed. */
  ipCidr?: string;
  managementProfile?: string;
  zone: string;
}

export interface PanOsZoneView {
  name: string;
  interfaces: string[];
}

export interface PanOsStaticRouteView {
  /** PAN-OS static routes are named, not sequence-numbered: "corp-data-via-ethernet1-2". */
  name: string;
  destination: string;
  nextHop: string;
  interfaceName: string;
  metric: number;
}

export interface PanOsView {
  banner: string;
  hostname: string;
  virtualRouter: string;
  /** Only emitted when there is more than one next hop, i.e. when the routes actually load-share. */
  ecmp: boolean;
  managementProfile: string | null;
  interfaces: PanOsInterfaceView[];
  zones: PanOsZoneView[];
  staticRoutes: PanOsStaticRouteView[];
}

/**
 * Builds the view model for a paloalto-panos edge firewall. Deliberately the
 * same posture the founder approved for FortiGate, expressed in PAN-OS syntax:
 *  - ethernet1/1 is the WAN uplink as a DHCP client (the ISP link isn't ours
 *    to address), taking the provider's default route.
 *  - Each modeled router-facing interface (device.interfaces with an ip)
 *    becomes a static inside port (ethernet1/2, ethernet1/3, …).
 *  - Zones: ethernet1/1 in "untrust", every inside port in "trust".
 *  - Static routes to each VLAN subnet via BOTH router /31 peer IPs, with the
 *    virtual router's ECMP enabled when there is more than one next hop, so
 *    the site survives a single router loss (matching HSRP intent).
 *  - NO security policies and NO NAT — interfaces + routing only, same as the
 *    FortiGate template. PAN-OS therefore denies interzone traffic until the
 *    engineer writes policy, which is the intended "base config" posture.
 */
export function buildPanOsView(device: Device, design: Design): PanOsView {
  const modeled = (device.interfaces ?? []).filter((iface) => iface.ip);

  const interfaces: PanOsInterfaceView[] = [
    { name: "ethernet1/1", comment: "wan-uplink", mode: "dhcp", zone: PANOS_UNTRUST_ZONE },
  ];
  const routerPorts: Array<{ portName: string; peerIp: string }> = [];

  modeled.forEach((iface, index) => {
    const portName = `ethernet1/${index + 2}`;
    interfaces.push({
      name: portName,
      comment: iface.description ?? portName,
      mode: "static",
      ipCidr: iface.ip!,
      managementProfile: PANOS_PING_PROFILE,
      zone: PANOS_TRUST_ZONE,
    });

    const peerIp = routerPeerIp(device, iface.name, design);
    if (peerIp) {
      routerPorts.push({ portName, peerIp });
    }
  });

  const zones: PanOsZoneView[] = [
    { name: PANOS_UNTRUST_ZONE, interfaces: ["ethernet1/1"] },
    { name: PANOS_TRUST_ZONE, interfaces: interfaces.filter((i) => i.mode === "static").map((i) => i.name) },
  ].filter((zone) => zone.interfaces.length > 0);

  const staticRoutes: PanOsStaticRouteView[] = [];
  const usedNames = new Set<string>();
  for (const segment of design.segments) {
    if (!segment.cidr) continue;
    for (const routerPort of routerPorts) {
      staticRoutes.push({
        name: uniqueRouteName(`${segment.name}-via-${routerPort.portName}`, usedNames),
        destination: segment.cidr,
        nextHop: routerPort.peerIp,
        interfaceName: routerPort.portName,
        metric: PANOS_ROUTE_METRIC,
      });
    }
  }

  return {
    banner: PANOS_BANNER,
    hostname: device.hostname ?? device.id,
    virtualRouter: PANOS_VIRTUAL_ROUTER,
    ecmp: routerPorts.length > 1,
    managementProfile: interfaces.some((i) => i.managementProfile) ? PANOS_PING_PROFILE : null,
    interfaces,
    zones,
    staticRoutes,
  };
}

/**
 * PAN-OS object names allow letters, digits, spaces, dots, hyphens and
 * underscores — notably NOT the "/" in an interface name — so
 * "corp-data-via-ethernet1/2" is sanitized to "corp-data-via-ethernet1-2".
 * Names must also be unique within the virtual router; a collision (two
 * segments whose sanitized names coincide) gets a numeric suffix rather than
 * silently overwriting the earlier route.
 */
function uniqueRouteName(raw: string, used: Set<string>): string {
  const base = raw.replace(/[^A-Za-z0-9._-]/g, "-");
  let name = base;
  let suffix = 2;
  while (used.has(name)) {
    name = `${base}-${suffix++}`;
  }
  used.add(name);
  return name;
}
