import type { Design, Device } from "@netdesign/schema";
import { cidrToIpAndMask, invertMask } from "./cidr.js";
import { toCiscoInterfaceName } from "./interface-naming.js";

export const BANNER = "! Base configuration generated by NetDesign.app — validate in a lab before production.";

export interface RouterPhysicalInterfaceView {
  name: string;
  description: string;
  ip: string;
  netmask: string;
}

export interface RouterSubinterfaceView {
  vlanId: number;
  ip: string;
  netmask: string;
  hsrp: { group: number; virtualIp: string; priority: number } | null;
}

export interface RouterTrunkView {
  name: string;
  description: string;
  subinterfaces: RouterSubinterfaceView[];
}

export interface RouterOspfView {
  processId: number;
  networks: Array<{ network: string; wildcard: string; area: string }>;
}

export interface RouterView {
  banner: string;
  hostname: string;
  physicalInterfaces: RouterPhysicalInterfaceView[];
  trunkInterfaces: RouterTrunkView[];
  ospf: RouterOspfView | null;
  defaultRouteNextHop: string | null;
}

/**
 * Builds the view model for a cisco-ios router: router-on-a-stick
 * subinterfaces per VLAN (one per `interfaces[].svis` entry — see
 * design-engine's assignInterfaces()), HSRP standby config when this
 * router shares a redundancyGroup with a peer, OSPF (only if
 * `routing.igp === "ospf"` — none of today's golden scenarios set that,
 * this composer always uses "static"), and a default route toward
 * whichever P2P-linked peer has role "firewall".
 *
 * NAT overload (BUILD_PLAN Session 10's other named item) is deliberately
 * NOT implemented: in every topology this composer can produce, a router
 * never has direct outside/internet connectivity — that link only ever
 * exists when a firewall is present, and it terminates on the firewall,
 * not the router (see branch-office.ts's buildLogicalLinks). Writing NAT
 * config here would be speculative and untestable against any real
 * scenario; add it once a topology actually needs it.
 */
export function buildRouterView(device: Device, design: Design): RouterView {
  const interfaces = device.interfaces ?? [];

  const physicalInterfaces: RouterPhysicalInterfaceView[] = interfaces
    .filter((iface) => iface.ip && !iface.trunk)
    .map((iface) => {
      const { ip, netmask } = cidrToIpAndMask(iface.ip!);
      return { name: toCiscoInterfaceName(iface.name), description: iface.description ?? "", ip, netmask };
    });

  const trunkInterfaces: RouterTrunkView[] = interfaces
    .filter((iface) => iface.trunk && (iface.svis?.length ?? 0) > 0)
    .map((iface) => ({
      name: toCiscoInterfaceName(iface.name),
      description: iface.description ?? "",
      subinterfaces: iface.svis!.map((svi) => {
        const { ip, netmask } = cidrToIpAndMask(svi.ip);
        return { vlanId: svi.vlanId, ip, netmask, hsrp: buildHsrp(device, design, svi.vlanId) };
      }),
    }));

  return {
    banner: BANNER,
    hostname: device.hostname ?? device.id,
    physicalInterfaces,
    trunkInterfaces,
    ospf: design.routing?.igp === "ospf" ? buildOspf(design) : null,
    defaultRouteNextHop: design.routing?.defaultRoute ? findDefaultRouteNextHop(device, design) : null,
  };
}

function buildHsrp(
  device: Device,
  design: Design,
  vlanId: number,
): { group: number; virtualIp: string; priority: number } | null {
  if (design.routing?.firstHopRedundancy !== "hsrp" || !device.redundancyGroup) {
    return null;
  }
  const segment = design.segments.find((s) => s.vlanId === vlanId);
  if (!segment?.gateway) {
    return null;
  }
  // Deterministic active/standby split: the alphabetically-first device id in the
  // redundancy group is active (priority 110); everyone else is standby (100).
  const peerIds = design.devices
    .filter((d) => d.redundancyGroup === device.redundancyGroup)
    .map((d) => d.id)
    .sort();
  const isActive = peerIds[0] === device.id;
  return { group: vlanId, virtualIp: segment.gateway, priority: isActive ? 110 : 100 };
}

function buildOspf(design: Design): RouterOspfView {
  const networks = design.segments.map((segment) => {
    const { ip, netmask } = cidrToIpAndMask(segment.cidr);
    return { network: ip, wildcard: invertMask(netmask), area: design.routing?.ospfAreas?.[0]?.area ?? "0" };
  });
  return { processId: 1, networks };
}

/** Finds the IP of whichever P2P-linked peer has role "firewall" — this composer's topology always routes a site's default route through its edge firewall, never directly out a router interface. */
function findDefaultRouteNextHop(device: Device, design: Design): string | null {
  for (const link of design.links) {
    const [aId, aIfaceName] = splitEndpoint(link.a);
    const [bId, bIfaceName] = splitEndpoint(link.b);

    let peerId: string | undefined;
    let peerIfaceName: string | undefined;
    if (aId === device.id) {
      [peerId, peerIfaceName] = [bId, bIfaceName];
    } else if (bId === device.id) {
      [peerId, peerIfaceName] = [aId, aIfaceName];
    } else {
      continue;
    }

    const peer = design.devices.find((d) => d.id === peerId);
    if (peer?.role !== "firewall") continue;

    const peerIface = (peer.interfaces ?? []).find((iface) => iface.name === peerIfaceName);
    if (peerIface?.ip) {
      return cidrToIpAndMask(peerIface.ip).ip;
    }
  }
  return null;
}

function splitEndpoint(endpoint: string): [string, string | undefined] {
  const [id, iface] = endpoint.split(":");
  return [id ?? endpoint, iface];
}

export interface SwitchVlanView {
  id: number;
  name: string;
}

export interface SwitchTrunkPortView {
  name: string;
  description: string;
  allowedVlans: string;
}

export interface SwitchView {
  banner: string;
  hostname: string;
  vlans: SwitchVlanView[];
  trunkPorts: SwitchTrunkPortView[];
}

/** Builds the view model for a cisco-ios access switch: the global VLAN database, and each trunk port's allowed-VLAN list. Access switches are L2-only in this composer — no SVIs, no routing. */
export function buildSwitchView(device: Device, design: Design): SwitchView {
  const interfaces = device.interfaces ?? [];

  const trunkPorts: SwitchTrunkPortView[] = interfaces
    .filter((iface) => iface.trunk)
    .map((iface) => ({
      name: toCiscoInterfaceName(iface.name),
      description: iface.description ?? "",
      allowedVlans: (iface.allowedVlans ?? []).join(","),
    }));

  const vlans: SwitchVlanView[] = design.segments
    .filter((segment): segment is typeof segment & { vlanId: number } => segment.vlanId !== undefined)
    .map((segment) => ({ id: segment.vlanId, name: segment.name }));

  return { banner: BANNER, hostname: device.hostname ?? device.id, vlans, trunkPorts };
}
