import type { Design, Device } from "@netdesign/schema";
import { cidrToIpAndMask, cidrToNetworkAndWildcard } from "./cidr.js";
import { toCiscoInterfaceName } from "./interface-naming.js";
import { peerDeviceIdOf, splitEndpoint } from "./peers.js";

export const BANNER = "! Base configuration generated by NetDesign.app — validate in a lab before production.";

export interface RouterPhysicalInterfaceView {
  name: string;
  description: string;
  ip: string;
  netmask: string;
}

export interface RouterSubinterfaceView {
  vlanId: number;
  ip: string;
  netmask: string;
  hsrp: { group: number; virtualIp: string; priority: number } | null;
}

export interface RouterTrunkView {
  name: string;
  description: string;
  subinterfaces: RouterSubinterfaceView[];
}

export interface RouterOspfView {
  processId: number;
  networks: Array<{ network: string; wildcard: string; area: string }>;
  /** Interfaces whose subnet is advertised into OSPF but that must not form an adjacency — the peer isn't an OSPF speaker (e.g. an edge router's firewall link, or a distribution SVI facing L2 access). */
  passiveInterfaces: string[];
}

export interface RouterView {
  banner: string;
  hostname: string;
  physicalInterfaces: RouterPhysicalInterfaceView[];
  trunkInterfaces: RouterTrunkView[];
  ospf: RouterOspfView | null;
  defaultRouteNextHop: string | null;
}

/**
 * Builds the view model for a cisco-ios router: router-on-a-stick
 * subinterfaces per VLAN (one per `interfaces[].svis` entry — see
 * design-engine's assignInterfaces()), HSRP standby config when this
 * router shares a redundancyGroup with a peer, OSPF (only if
 * `routing.igp === "ospf"` — none of today's golden scenarios set that,
 * this composer always uses "static"), and a default route toward
 * whichever P2P-linked peer has role "firewall".
 *
 * NAT overload (BUILD_PLAN Session 10's other named item) is deliberately
 * NOT implemented: in every topology this composer can produce, a router
 * never has direct outside/internet connectivity — that link only ever
 * exists when a firewall is present, and it terminates on the firewall,
 * not the router (see branch-office.ts's buildLogicalLinks). Writing NAT
 * config here would be speculative and untestable against any real
 * scenario; add it once a topology actually needs it.
 */
export function buildRouterView(device: Device, design: Design): RouterView {
  const interfaces = device.interfaces ?? [];

  const physicalInterfaces: RouterPhysicalInterfaceView[] = interfaces
    .filter((iface) => iface.ip && !iface.trunk)
    .map((iface) => {
      const { ip, netmask } = cidrToIpAndMask(iface.ip!);
      return { name: toCiscoInterfaceName(iface.name), description: iface.description ?? "", ip, netmask };
    });

  const trunkInterfaces: RouterTrunkView[] = interfaces
    .filter((iface) => iface.trunk && (iface.svis?.length ?? 0) > 0)
    .map((iface) => ({
      name: toCiscoInterfaceName(iface.name),
      description: iface.description ?? "",
      subinterfaces: iface.svis!.map((svi) => {
        const { ip, netmask } = cidrToIpAndMask(svi.ip);
        return { vlanId: svi.vlanId, ip, netmask, hsrp: buildHsrp(device, design, svi.vlanId) };
      }),
    }));

  return {
    banner: BANNER,
    hostname: device.hostname ?? device.id,
    physicalInterfaces,
    trunkInterfaces,
    ospf: buildOspfForDevice(device, design),
    defaultRouteNextHop: design.routing?.defaultRoute ? findDefaultRouteNextHop(device, design) : null,
  };
}

function buildHsrp(
  device: Device,
  design: Design,
  vlanId: number,
): { group: number; virtualIp: string; priority: number } | null {
  if (design.routing?.firstHopRedundancy !== "hsrp" || !device.redundancyGroup) {
    return null;
  }
  const segment = design.segments.find((s) => s.vlanId === vlanId);
  if (!segment?.gateway) {
    return null;
  }
  // Deterministic active/standby split: the alphabetically-first device id in the
  // redundancy group is active (priority 110); everyone else is standby (100).
  const peerIds = design.devices
    .filter((d) => d.redundancyGroup === device.redundancyGroup)
    .map((d) => d.id)
    .sort();
  const isActive = peerIds[0] === device.id;
  return { group: vlanId, virtualIp: segment.gateway, priority: isActive ? 110 : 100 };
}

/**
 * Builds OSPF from the networks THIS device is actually connected to — its
 * routed physical interfaces, its SVIs (the VLAN subnet, not the host bits),
 * and its loopback — rather than blindly advertising every VLAN in the design.
 * That matters for the campus fabric: a core switch advertises only its /31
 * transit links + loopback (it has no VLANs), while a distribution switch
 * advertises its SVI subnets AND its /31 uplinks so an adjacency can form. The
 * OSPF area is whichever `routing.ospfAreas` entry lists this device (falling
 * back to the first area, then "0"). Returns null unless the design runs OSPF.
 */
function buildOspfForDevice(device: Device, design: Design): RouterOspfView | null {
  if (design.routing?.igp !== "ospf") {
    return null;
  }
  const area =
    design.routing.ospfAreas?.find((a) => a.deviceIds?.includes(device.id))?.area ??
    design.routing.ospfAreas?.[0]?.area ??
    "0";

  const networks: RouterOspfView["networks"] = [];
  const seen = new Set<string>();
  const addNetwork = (cidr: string) => {
    const { network, wildcard } = cidrToNetworkAndWildcard(cidr);
    const key = `${network} ${wildcard}`;
    if (!seen.has(key)) {
      seen.add(key);
      networks.push({ network, wildcard, area });
    }
  };

  // An interface is passive if its subnet is in OSPF but its peer doesn't speak
  // OSPF — hellos there would go unanswered (an edge router's firewall link).
  const speakers = ospfSpeakerIds(design);
  const passiveInterfaces: string[] = [];

  if (device.loopback) addNetwork(device.loopback);
  for (const iface of device.interfaces ?? []) {
    if (iface.ip && !iface.trunk) {
      addNetwork(iface.ip);
      const peerId = peerDeviceIdOf(device.id, iface.name, design);
      if (peerId && !speakers.has(peerId)) {
        passiveInterfaces.push(toCiscoInterfaceName(iface.name));
      }
    }
    for (const svi of iface.svis ?? []) addNetwork(svi.ip);
  }

  return { processId: 1, networks, passiveInterfaces };
}

/** The set of device ids that actually run OSPF (the union of `routing.ospfAreas[].deviceIds`) — used to decide which interfaces should be passive. */
function ospfSpeakerIds(design: Design): Set<string> {
  const ids = new Set<string>();
  for (const area of design.routing?.ospfAreas ?? []) {
    for (const id of area.deviceIds ?? []) ids.add(id);
  }
  return ids;
}

/** Finds the IP of whichever P2P-linked peer has role "firewall" — this composer's topology always routes a site's default route through its edge firewall, never directly out a router interface. */
function findDefaultRouteNextHop(device: Device, design: Design): string | null {
  for (const link of design.links) {
    const [aId, aIfaceName] = splitEndpoint(link.a);
    const [bId, bIfaceName] = splitEndpoint(link.b);

    let peerId: string | undefined;
    let peerIfaceName: string | undefined;
    if (aId === device.id) {
      [peerId, peerIfaceName] = [bId, bIfaceName];
    } else if (bId === device.id) {
      [peerId, peerIfaceName] = [aId, aIfaceName];
    } else {
      continue;
    }

    const peer = design.devices.find((d) => d.id === peerId);
    if (peer?.role !== "firewall") continue;

    const peerIface = (peer.interfaces ?? []).find((iface) => iface.name === peerIfaceName);
    if (peerIface?.ip) {
      return cidrToIpAndMask(peerIface.ip).ip;
    }
  }
  return null;
}

export interface SwitchVlanView {
  id: number;
  name: string;
}

export interface SwitchTrunkPortView {
  name: string;
  description: string;
  allowedVlans: string;
}

export interface SwitchView {
  banner: string;
  hostname: string;
  vlans: SwitchVlanView[];
  trunkPorts: SwitchTrunkPortView[];
}

/** Builds the view model for a cisco-ios access switch: the global VLAN database, and each trunk port's allowed-VLAN list. Access switches are L2-only in this composer — no SVIs, no routing. */
export function buildSwitchView(device: Device, design: Design): SwitchView {
  const interfaces = device.interfaces ?? [];

  const trunkPorts: SwitchTrunkPortView[] = interfaces
    .filter((iface) => iface.trunk)
    .map((iface) => ({
      name: toCiscoInterfaceName(iface.name),
      description: iface.description ?? "",
      allowedVlans: (iface.allowedVlans ?? []).join(","),
    }));

  const vlans: SwitchVlanView[] = design.segments
    .filter((segment): segment is typeof segment & { vlanId: number } => segment.vlanId !== undefined)
    .map((segment) => ({ id: segment.vlanId, name: segment.name }));

  return { banner: BANNER, hostname: device.hostname ?? device.id, vlans, trunkPorts };
}

export interface RoutedPortView {
  name: string;
  description: string;
  ip: string;
  netmask: string;
}

export interface SwitchSviView {
  vlanId: number;
  ip: string;
  netmask: string;
  hsrp: { group: number; virtualIp: string; priority: number } | null;
}

export interface DistributionSwitchView {
  banner: string;
  hostname: string;
  vlans: SwitchVlanView[];
  svis: SwitchSviView[];
  routedPorts: RoutedPortView[];
  trunkPorts: SwitchTrunkPortView[];
  ospf: RouterOspfView | null;
}

/**
 * Builds the view model for a cisco-ios L3 distribution switch — the campus
 * VLAN-gateway tier. It carries: the global VLAN database; one routed SVI
 * (`interface VlanN`) per VLAN with HSRP standby config (the SVIs live on the
 * device's access-facing trunk under `interfaces[].svis`, anchored to a single
 * trunk by design-engine so we emit each SVI once); routed /31 uplink ports to
 * the core (`no switchport`); L2 trunk downlink ports to the access layer; and
 * OSPF over its connected networks. `ip routing` is enabled by the template.
 */
export function buildDistributionSwitchView(device: Device, design: Design): DistributionSwitchView {
  const interfaces = device.interfaces ?? [];

  const vlans: SwitchVlanView[] = design.segments
    .filter((segment): segment is typeof segment & { vlanId: number } => segment.vlanId !== undefined)
    .map((segment) => ({ id: segment.vlanId, name: segment.name }));

  const svis: SwitchSviView[] = interfaces
    .flatMap((iface) => iface.svis ?? [])
    .map((svi) => {
      const { ip, netmask } = cidrToIpAndMask(svi.ip);
      return { vlanId: svi.vlanId, ip, netmask, hsrp: buildHsrp(device, design, svi.vlanId) };
    });

  const routedPorts: RoutedPortView[] = interfaces
    .filter((iface) => iface.ip && !iface.trunk)
    .map((iface) => {
      const { ip, netmask } = cidrToIpAndMask(iface.ip!);
      return { name: toCiscoInterfaceName(iface.name), description: iface.description ?? "", ip, netmask };
    });

  const trunkPorts: SwitchTrunkPortView[] = interfaces
    .filter((iface) => iface.trunk)
    .map((iface) => ({
      name: toCiscoInterfaceName(iface.name),
      description: iface.description ?? "",
      allowedVlans: (iface.allowedVlans ?? []).join(","),
    }));

  // The SVIs face the L2 access layer (hosts), never an OSPF neighbor, so they
  // advertise their subnet but stay passive — no OSPF hellos toward end users.
  const ospf = buildOspfForDevice(device, design);
  if (ospf) {
    ospf.passiveInterfaces.push(...svis.map((svi) => `Vlan${svi.vlanId}`));
  }

  return {
    banner: BANNER,
    hostname: device.hostname ?? device.id,
    vlans,
    svis,
    routedPorts,
    trunkPorts,
    ospf,
  };
}

export interface CoreSwitchView {
  banner: string;
  hostname: string;
  routedPorts: RoutedPortView[];
  ospf: RouterOspfView | null;
}

/**
 * Builds the view model for a cisco-ios L3 core switch — pure routed transit.
 * Every interface is a routed /31 (`no switchport`); there are no VLANs, no
 * SVIs, and no host-facing trunks. OSPF advertises its connected /31 links and
 * loopback. `ip routing` is enabled by the template.
 */
export function buildCoreSwitchView(device: Device, design: Design): CoreSwitchView {
  const interfaces = device.interfaces ?? [];

  const routedPorts: RoutedPortView[] = interfaces
    .filter((iface) => iface.ip && !iface.trunk)
    .map((iface) => {
      const { ip, netmask } = cidrToIpAndMask(iface.ip!);
      return { name: toCiscoInterfaceName(iface.name), description: iface.description ?? "", ip, netmask };
    });

  return {
    banner: BANNER,
    hostname: device.hostname ?? device.id,
    routedPorts,
    ospf: buildOspfForDevice(device, design),
  };
}
